kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.volume.persistentVolumeClaimName }}
  labels:
    app: {{ .Values.appName }}
spec:
  storageClassName: manual
  accessModes:
    - {{ .Values.volume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.volume.storage }}