apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.appName }}
  labels:
    app: {{ .Values.frontend.appName }}
    tier: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.appName }}
      tier: {{ .Values.frontend.service.spec.selector.tier }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.appName }}
        tier: {{ .Values.frontend.service.spec.selector.tier }}
    spec: # Pod spec
      containers:
        - name: {{ .Values.frontend.containerName }}
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ .Values.frontend.config.name }}