name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for backend
      run: |
        echo "${{secrets.DOCKER_PW}}" | docker login -u "martinrudnikovski" --password-stdin 
        docker image build ./backend --file Dockerfile
        docker push martinrudnikovski/backend:latest

    - uses: actions/checkout@v3
    - name: Build the Docker image for frontend
      run: |
        echo "${{secrets.DOCKER_PW}}" | docker login -u "martinrudnikovski" --password-stdin 
        docker image build ./backend --file Dockerfile 
        docker push martinrudnikovski/frontend:latest
