name: Deploy
on:
  push:
    branches:
      ["master"]
jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: |
            helm upgrade backend ./helmCharts/backend --install --wait --atomic --namespace=test
            helm upgrade frontend ./helmCharts/frontend --install --wait --atomic --namespace=test
          kubeconfig: '${{ secrets.KUBECONFIG }}'
